### ISSUE TITLE
Eccezioni non gestite

### ISSUE THREAD

**Issue by FoxySeta** [csunibo/informabot#34]
Ci sono eccezioni non gestite. Forse controllando il log le si puo' identificare meglio.
Per esempio:
```
Oct 09 20:46:54 Telegram-Bot node[29814]: RequestError: Error: read ETIMEDOUT
Oct 09 20:46:54 Telegram-Bot node[29814]:     at new RequestError (/home/debian/bot/node_modules/request-promise-core/lib/errors.js:14:15)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at Request.plumbing.callback (/home/debian/bot/node_modules/request-promise-core/lib/plumbing.js:87:29)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at Request.RP$callback [as _callback] (/home/debian/bot/node_modules/request-promise-core/lib/plumbing.js:46:31)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at self.callback (/home/debian/bot/node_modules/request/request.js:185:22)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at Request.emit (events.js:314:20)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at Request.onRequestError (/home/debian/bot/node_modules/request/request.js:877:8)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at ClientRequest.emit (events.js:314:20)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at TLSSocket.socketErrorListener (_http_client.js:427:9)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at TLSSocket.emit (events.js:314:20)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Oct 09 20:46:54 Telegram-Bot node[29814]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Oct 09 20:46:54 Telegram-Bot node[29814]:   code: 'EFATAL'
Oct 09 20:46:54 Telegram-Bot node[29814]: }
```

**Comment by FoxySeta** [comment]
Si verificano ancora.
